# Generated by Django 3.2.15 on 2023-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block_file_map',
            fields=[
                ('hash', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('path', models.TextField(null=True)),
                ('token', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Csrf_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('hash', models.TextField(max_length=80)),
                ('loc', models.TextField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('is_alive', models.IntegerField(default=1)),
            ],
        ),
    ]
